# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.16"
  amd64: "ghcr.io/home-assistant/amd64-base:3.16"
  armhf: "ghcr.io/home-assistant/armhf-base:3.16"
  armv7: "ghcr.io/home-assistant/armv7-base:3.16"
  i386: "ghcr.io/home-assistant/i386-base:3.16"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Netdata"
  org.opencontainers.image.description: "Netdata https://www.netdata.cloud/ Monitor everything in real time. For free"
  org.opencontainers.image.source: "https://github.com/Gamma-Software/netdata-homeassistant-addon"
  org.opencontainers.image.licenses: "MIT License"
  org.opencontainers.image.version: "2.2.0"
