# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Netdata
version: "2.1.2"
slug: netdata
description: Netdata - Monitor everything in real time
url: "https://github.com/Gamma-Software/netdata-homeassistant-addon"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
panel_icon: mdi:chart-bell-curve
panel_title: Netdata
ingress: true
ingress_port: 19999
journald: true
privileged:
  - SYS_PTRACE
options:
  hostname: homeassistant
  page_cache_size: 32
  dbengine_disk_space: 256
  enable_alarm: true
  enable_log: true
  claim_url: https://app.netdata.cloud
  claim_token: xxxxxxxxxxxxxxxxxxxxxxx
  claim_rooms:
    - ROOM
schema:
  hostname: str
  page_cache_size: int
  dbengine_disk_space: int
  enable_alarm: bool
  enable_log: bool
  claim_url: str
  claim_token: str
  claim_rooms:
    - str
image: "ghcr.io/gamma-software/{arch}-netdata-homeassistant-addon"
